# 📑Introduction to Numpy

## ➡️Why Numpy?

• It's fast

• Behind the scenes optimizations written in C

• Vectorization via broadcasting (avoiding loops)

• Backbone of other Python scientific packages

In [2]:
import numpy as np

## ➡️Datatypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],
                [4,5,6]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])



In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a1.ndim, a2.ndim, a3.ndim

## Number of dimensions

(1, 2, 3)

In [12]:
a1.dtype

dtype('int32')

In [13]:
a2.dtype

dtype('int32')

In [14]:
a1.size

#number of elements

3

In [16]:
# Creating DataFrame from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## ➡️Creating Arrays

In [17]:
ones = np.ones((3,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros = np.zeros((3,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(1, 20 , 5)
range_array

# arange([start]stop[step])

# It will going to start from 1 , stop at 20 and number of gaps will be 5

array([ 1,  6, 11, 16])

In [23]:
ra = np.arange(10, 50 , 2)
ra


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [24]:
# Creating random numbers 

# It will create random number from 1 to 50 into size of 2 rows and 4 number into it.
random_array = np.random.randint(1, 50 , size=(2,4))


In [27]:
random_array

array([[32, 47, 26, 41],
       [24, 33, 33,  9]])

In [28]:
random_array.size

8

In [29]:
random_array.shape

(2, 4)

In [30]:
ra_1 = np.random.random((4,5))
ra_1

array([[0.37470621, 0.77636936, 0.41326477, 0.10382518, 0.07758734],
       [0.3192203 , 0.42211682, 0.99657466, 0.81194068, 0.18100365],
       [0.89287531, 0.79637314, 0.3874426 , 0.25986396, 0.75699728],
       [0.29244162, 0.9774838 , 0.28311526, 0.84213141, 0.31190808]])

In [31]:
ra_2 = np.random.rand(5,3)

In [32]:
ra_2

array([[0.70258729, 0.51552035, 0.81021452],
       [0.42704904, 0.60677727, 0.33544614],
       [0.05885911, 0.04355595, 0.80604116],
       [0.36401158, 0.08167946, 0.01923243],
       [0.19177249, 0.35142736, 0.91723506]])

In [45]:
#Pseudo-random numbers
np.random.seed(seed=10)
random_array
 

array([[32, 47, 26, 41],
       [24, 33, 33,  9]])

## ➡️Viewing arrays and matrices

In [54]:
np.unique(random_array)

array([ 9, 24, 26, 32, 33, 41, 47])

In [47]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a2[1]

array([4, 5, 6])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [59]:
a4 = np.random.randint(50, size=(4,5))
a4

array([[ 9,  0, 42, 40, 36],
       [16, 36, 47, 11, 24],
       [43, 33,  8, 36, 14],
       [49, 13,  5, 13, 25]])

In [64]:
# Get the first 3 numbers of the inner most arrays

a4[:, :3]

array([[ 9,  0, 42],
       [16, 36, 47],
       [43, 33,  8],
       [49, 13,  5]])

In [65]:
a4[:, :1]

array([[ 9],
       [16],
       [43],
       [49]])

## ➡️Manipulating & Comparing Arrays

### ⬇️Arithmetic

In [67]:
a1

array([1, 2, 3])

In [68]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [70]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [71]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [72]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [75]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [76]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

### ⬇️Aggregation

Aggregation = performing the same operation on a number of things


In [77]:
l1 = [ 1, 2, 3 ]
type(l1)


list

In [78]:
sum(l1)

6

In [79]:
a1

array([1, 2, 3])

In [80]:
type(a1)

numpy.ndarray

In [81]:
sum(a1)

6

In [82]:
# standard Deviation
np.std(a2)

1.707825127659933

In [83]:
# variance
np.var(a2)

2.9166666666666665

In [84]:
# standard Deviation = squareroot of variance
np.sqrt(np.var(a2))

1.707825127659933

## ➡️Reshaping & Transposing


In [85]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
ar = a2.reshape(2,3,1)
ar

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [91]:
ar * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [92]:
# Transpose
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## ➡️Dot Product